
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - streaming.srs
  resources:
  - srsclusternginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.srs
  resources:
  - srsclusternginxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - streaming.srs
  resources:
  - srsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.srs
  resources:
  - srsclusters/status
  verbs:
  - get
  - patch
  - update
