# permissions for end users to edit srsclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: srscluster-editor-role
rules:
- apiGroups:
  - streaming.srs
  resources:
  - srsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.srs
  resources:
  - srsclusters/status
  verbs:
  - get
