# permissions for end users to view srsclusternginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: srsclusternginx-viewer-role
rules:
- apiGroups:
  - streaming.srs
  resources:
  - srsclusternginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streaming.srs
  resources:
  - srsclusternginxes/status
  verbs:
  - get
