# permissions for end users to edit srsclusternginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: srsclusternginx-editor-role
rules:
- apiGroups:
  - streaming.srs
  resources:
  - srsclusternginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.srs
  resources:
  - srsclusternginxes/status
  verbs:
  - get
