# permissions for end users to view srsclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: srscluster-viewer-role
rules:
- apiGroups:
  - streaming.srs
  resources:
  - srsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streaming.srs
  resources:
  - srsclusters/status
  verbs:
  - get
